### ISSUE TITLE
"Join our mailing list" footer button left

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#116]
We must have added some CSS rules for the Events that made the footer button for join our mailing list go to the left on small screen sizes. We need to change the CSS so that the buttons in the footer and the Events stay where they should be without interfering with each other.

**Comment by nurgul-ths** [comment]
I added a margin-left of 10% when width is less than 750, does that look fine?
![Screenshot 2021-05-07 at 01 28 12](https://user-images.githubusercontent.com/79397892/117354773-90774480-aed3-11eb-9cf8-d9730bb6c284.png)

**Comment by Jhappy77** [comment]
I think we want it completely centered
