### ISSUE TITLE
Remove arrow in Visit GitHub button

### ISSUE THREAD

**Issue by nurgul-ths** [Tech-Start-UCalgary/tsu-website#120]
Would it look better if we remove the arrow in the Visit GitHub button? When width is less than 400, the arrow goes down since there isn't enough space for it
![Screenshot 2021-05-07 at 01 30 16](https://user-images.githubusercontent.com/79397892/117355147-ffed3400-aed3-11eb-801a-2bfb3ddd2c7b.png)

**Comment by Jhappy77** [comment]
Yeah feel free to. We could also increase the size of the button to handle it
