### ISSUE TITLE
No cursor hover on navbar menu icon

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#14]
When the navbar menu is in the collapsed mode (hamburger menu icon appears), your cursor should change to a pointer when hovering over the menu button to show that it's a button. Should be a quick fix, can you do this @zNon18 ?

**Comment by zNon18** [comment]
Fixed it! Thank you for pointing that out. 
https://www.loom.com/share/0f9077fbbfbe4245a0556f039aa696d6

**Comment by Jhappy77** [comment]
Sweet. For practice, close this issue!

**Comment by zNon18** [comment]
Fixed no cursor hover on navbar menu icon
