### ISSUE TITLE
Squished event images

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#142]
![image](https://user-images.githubusercontent.com/45266424/117496154-dcf26c80-af33-11eb-8432-a21541098c27.png)

Event images squish far too much on screen size changes
My thoughts:
- We should guarantee that all images for events have the same aspect ratio (Perhaps a square, like Instagram, or the aspect ratio that Facebook uses for its event banners?). Guarantee in the CSS that this aspect ratio doesn't change. 
- In addition to the above point, we could make it so that the event images take up a 100% height of the event component and size everything accordingly?

**Comment by Niyousha99** [comment]
I didn't realize this issue existed but I think I fixed it in my most recent commit. Let me know if it's resolved!
