### ISSUE TITLE
Consider changing aesthetics of landing page

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#147]
We may want to change the background of the landing page. Some ideas:
- Image background: we can do this but it sometimes has trouble loading
- SVG background: there are websites that have cool svg background generators https://www.svgbackgrounds.com
- Different gradient

Another note:
we can change the color of the particles too! Their parameters are in Particles.tsx. It would be cool to see if we could have multicolored particles and/or gradient lines. 

What are your thoughts on the current version of the landing page?

**Comment by Niyousha99** [comment]
I also think it would be nice to have one cohesive background for the landing page, maybe something with the same color scheme as the logo.
