### ISSUE TITLE
Navbar dropdown button glitches & delayed response

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#15]
Steps to reproduce:
1. Open the website on Firefox
2. Make your Firefox window small enough that the navbar collapses into the hamburger menu icon
3. Open and close the navbar by pressing the hamburger menu button. In between doing this, try clicking on other parts of the website

I tested this on 2 different firefox browsers and often times my clicks on the menu icon would simply not register, or nothing would happen. We should investigate and fix this issue.

This issue also seems to exist, but to a significantly lesser extent, on Google Chrome. It may be worth experimenting with additional browsers to see if any of them cause unexpected behaviors.

**Comment by Jhappy77** [comment]
> After fixing the cursor issue, the delayed response seems to get better, even on Firefox. (tested on edge as well) There is a small error when the cursor is between the lines of the hamburger menu.
> https://www.loom.com/share/702b2be646f14e7f9d86e7d10bd45fb8

Interesting.. Are you creating the icon thru styling css? You could probably fix the issue of it not working between the lines by surrounding the whole thing with an anchor tag (<A>) or a button <button>. If you make it a button you'll have to add a bunch of css to remove the default button styles that get applied. Once you have this issue fixed and tested across multiple browsers, we can do a pull request.

**Comment by zNon18** [comment]
Fixed the issue, due to nav-toggle being really weird. 
https://www.loom.com/share/3a2c73dfb5b24096a9426f29e499b092
