### ISSUE TITLE
Make Carousel wrap

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#16]
When on the first or last carousel item and you click left/right respectively, you should loop around to the other side- this will make it much easier to browse thru people! There should be a built in feature of the carousel that lets you do this.

**Comment by Niyousha99** [comment]
Will look into it!

**Comment by Niyousha99** [comment]
It seems like the creator of the package is still working on implementing the infinite loop feature: https://github.com/sag1v/react-elastic-carousel/issues/9

**Comment by Niyousha99** [comment]
Closing as we will be removing usage of this  `react-elastic-carousel` as part of #297
