### ISSUE TITLE
Register menu on low screen width

### ISSUE THREAD

**Issue by nurgul-ths** [Tech-Start-UCalgary/tsu-website#171]
Register popup menu seems to be stuck to the bottom of the page when the page is not displayed full screen, so the get started button and everything below it isn't visible. Should we make the menu appear full size? Though I'm not sure if it looks the same on the deployed version on mobile bc I can't find the link to the community page there.
![Screenshot 2021-05-17 at 18 57 50](https://user-images.githubusercontent.com/79397892/118499149-7a297e00-b748-11eb-966f-733f4b8617c6.png)

**Comment by Jhappy77** [comment]
We can change the styling of this menu to do the following things:

- Remove the Tech Start logo
- Put 'Register' as a title, similar to how it is for the Login thing
- Optional: have the same gradient siding that the login menu has (we could put it in SignIn so it applies to both Login and Register?
- Get rid of the "get started w" title
- Make the subtitle clear that you are making an account to interact with the community page
- Make it wider by default
- Reduce the vertical padding on the the fields (do this for Login too)

If we do all of those it should fix this problem :)
