### ISSUE TITLE
Reduce vertical padding on forms in community page

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#177]
The form fields on the community page have too much vertical padding IMO - we should make the padding smaller (you can research the ideal amount for a form field). They also turn blue after you fill them out - we should get rid of this effect. Thoughts @taylor-noel ?

![image](https://user-images.githubusercontent.com/45266424/119249327-e7784d00-bb54-11eb-81eb-04b74f12c225.png)

**Comment by taylor-noel** [comment]
ya i'll look into that

**Comment by taylor-noel** [comment]
fixed the blue and changed the padding to be 5px rather than 10px. I couldn't find anything on the internet for ideal styling so let me know what you think of it now and we can keep playing around

**Comment by Jhappy77** [comment]
@nurgul-ths Taylor did this so you don't have to
