### ISSUE TITLE
Footer Styling

### ISSUE THREAD

**Issue by nurgul-ths** [Tech-Start-UCalgary/tsu-website#189]
Apart from the icons' size and colour, is it ok if I work a bit on the footer's colour? We can keep the colour as it is rn, but I wanted to experiment and see if it will look better if we make the background darker, whereas the icons lighter? Like these websites do:
http://valaire.mu/
https://www.weareenvoy.com/

**Comment by Jhappy77** [comment]
Make a poll for this in our discord so we can decide what color we like the best! Feel free to make your own color combos (even if they include colors not defined in App.css)
