### ISSUE TITLE
No user-select on carousel buttons

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#19]
The < > buttons on the carousel shouldn't be able to be highlighted (ex for copy and paste) by the user. We can add some CSS to easily fix this! Read more about the user-select rule, it should be an easy fix. 
Here might be a good place to start:
https://stackoverflow.com/questions/826782/how-to-disable-text-selection-highlighting

**Comment by Niyousha99** [comment]
Added some CSS to remove user-select based on the link you pasted.
