### ISSUE TITLE
Carousel drag glitch

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#20]
If you try to drag the image inside the carousel (ex, pretend you're trying to swipe left/right but with your mouse) it glitches up massively (getting stuck between items, jittering, etc). We need to find some way to stop this from happening. If you're unable to reproduce this I can show you a video.

**Comment by Niyousha99** [comment]
Yeah I noticed and was able to reproduce the issue now that you mentioned it. I tried preventing the default drag handler for each image. It's smoother now on my side but let me know if the issue remains.
