### ISSUE TITLE
Favicon update

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#218]
We should update the favicon to be in sync with the new logo.
Logos are available under drive -> communication -> logoV2

If you use this website, you should be able to update the files without changing any code (as it's what I used before)
https://realfavicongenerator.net/

**Comment by nurgul-ths** [comment]
sorry what's favicon?

**Comment by Jhappy77** [comment]
@nurgul-ths It's the little icon that represents the website!
![image](https://user-images.githubusercontent.com/45266424/134751367-e411e1a8-4cab-4a99-a10c-7e39eaed890f.png)

**Comment by Niyousha99** [comment]
Done as part of #272
