### ISSUE TITLE
Mobile: Navbar gap

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#221]
On my mobile phone (using Safari), when I scroll down I can sometimes see a gap of a few px between the top of the navbar container and the boundaries of the Safari browser, allowing me to see the page behind it. 

 We should get rid of this small visual glitch. One possibility is to translate the navbar a couple px upwards (-2px?) at all times, and see if that fixes it.

**Comment by Niyousha99** [comment]
Closing this issue as it is related to Safari/iPhone limitations, not our website, and barely noticable.
