### ISSUE TITLE
Get rid of link to style guide - and instead, link the logo folder

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#226]
The resources page has a link to the style guide, but we don't have one. We don't want this for now.

Instead, we should provide a way to download the logos. They're in a folder in our drive called Logos V2 under communication. We need to ensure that people can download them, but not delete or alter them.

**Comment by Jhappy77** [comment]
@nurgul-ths Do you think you could take this one on?

**Comment by nurgul-ths** [comment]
yep I can!

**Comment by nurgul-ths** [comment]
we already have a link to the logos under "Logos" of the "Branding" section. I can change the text a bit to ensure that people can download them, but not delete or alter them. Should I delete the sentence about styling guide?

**Comment by Jhappy77** [comment]
Oh, sorry for not noticing!

Yeah, how about we comment out the text about the style guide. Let's also make the logos link point towards the Logos V2 folder
