### ISSUE TITLE
Apply Page Hero sizing

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#229]
The Apply page's hero sizing rules could be polished. Current issues:

- On laptops, the bottom of the "apply" subtitle reaches very close to the wavy section that divides the top from the bottom
- On small screens, the bottom left blobbie sometimes 
- The bottom left blobbie seems too large at small screen sizes and it will cover up a big portion of the text as well

Potential fixes:

- Configure the blobbies so that they can have a different transform for small screen sizes. Pass a different transform for small screen sizes to the bottom left blobbie so it doesn't cover so much
- Fine tune the 

As with anything that involves sizing, please test this thoroughly and extensively if you take this issue on. We don't want any unexpected behavior occurring at different pixel sizes (sometimes glitches occur in small unexpected pixel ranges).

**Comment by Niyousha99** [comment]
Closing issue as it has been split into 2 separate issues: #312 and #261
