### ISSUE TITLE
Home page logo loading

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#234]
The logo on the home page always takes a little while to load for me. We should investigate ways to reduce this loading time.
Potential solutions:
- Include a file with a smaller size (the time it takes to load may be associated with compressing the current image, which is pretty large)
- Making it fade in once it has fully loaded?

**Comment by Niyousha99** [comment]
Closing this issue as we have added a fade-in effect for the logo.
