### ISSUE TITLE
Improve UX and promote business strategy by restructuring sections/pages

### ISSUE THREAD

**Issue by Niyousha99** [Tech-Start-UCalgary/tsu-website#249]
AC:
To be better aligned with TSU's business strategy (user impression, engagement, and inclusivity):
- Update the "about us" section in the homepage 
- Come up with proposals on restructuring sections/pages (design prototypes)
- Solicit feedback from team and stakeholders

**Comment by TakahiroFujitaSJB** [comment]
The Current Plans for the website.
Home page: 
       **Keep:** Title, Description, Sponsors
       **Changes**:  
- Create "Project description" section below club description.
- Migrate "Past Projects" to new Projects page
- Format "Events" section so description of events are 'omitted' for mobile users.
- Migrate "Our Team" section

**Comment by Niyousha99** [comment]
The following issues/PRs have been created to address these changes:

- #278
- #296 
- #299 
- Team tab - #291
