### ISSUE TITLE
Align apply buttons on main page

### ISSUE THREAD

**Issue by Niyousha99** [Tech-Start-UCalgary/tsu-website#257]
The following buttons/links on the main page all redirect to the apply page:

1. - ">> theTeam.join()" button
2. - Find out what it takes to apply!" link at top of Team section
3. - "Join now" button at bottom of Team section 

AC:

- Remove excessive use of buttons/links which redirect to the same page. I suggest moving button 1 to the bottom of the team section and removing buttons 2 and 3. I am open to other suggestions as well.

**Comment by rfsayers** [comment]
Partially complete, text button removed and replaced with Join Now button. Future update of Join Now button to connect to planned "Teams"/"Projects" page
