### ISSUE TITLE
Remove duplicate FAQ section in Apply page

### ISSUE THREAD

**Issue by Niyousha99** [Tech-Start-UCalgary/tsu-website#289]
There are currently 2 separate FAQ sections on the Apply page:

![image](https://user-images.githubusercontent.com/59885733/146625242-f273c055-24d7-482a-8e22-6197c531ea96.png)
![image](https://user-images.githubusercontent.com/59885733/146625248-fca2dc80-7678-4b07-8874-ddcd6048de93.png)

I propose to move the 2 Q&A's from the second FAQ to the project FAQs section, and remove the second FAQ section.

**Comment by praguru14** [comment]
Hi, can I help on this?

**Comment by Niyousha99** [comment]
> Hi, can I help on this?

Hello, unfortunately we are not accepting contributors at the moment. Thank you.

**Comment by praguru14** [comment]
No issues :). Thanks for the response.
