### ISSUE TITLE
Glitched footer on laptop

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#294]
![image](https://user-images.githubusercontent.com/45266424/149452052-5d697890-554d-464c-a252-0727c7c4931f.png)

See attached

**Comment by Niyousha99** [comment]
Hey @Jhappy77, I was unable to reproduce this error on chrome and edge using Windows OS. Could you provide some more details on how to encountered this bug?

**Comment by Jhappy77** [comment]
This was on Firefox on Windows 10! Sorry for not including that before!
