### ISSUE TITLE
Redesign Team section on mobile view 

### ISSUE THREAD

**Issue by Niyousha99** [Tech-Start-UCalgary/tsu-website#297]
The carousel view for our team section is outdated and difficult to maintain. 

AC:

- Redesign team section for mobile view (screen width < 600px)
- Implement design in code

**Comment by Sahitiakella** [comment]
<img width="255" alt="Screen Shot 2022-02-17 at 5 38 19 PM" src="https://user-images.githubusercontent.com/63627104/154595535-b1ebcdb3-b6c3-4cab-9d3c-7ed221694e3a.png">
