### ISSUE TITLE
Update hierarchy of application importance

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#35]
The majority of users of the website will be looking to apply to be a team member, not a Project Manager or Exec- therefore I think it makes sense to put the team member application first.

This brings up another point that we should discuss: not everyone who joins a team will necessarily be a developer (we can have specialized business/strategy people or art/design people like we did this year). IMO, I think we should elaborate on what it means to join a team (detail the expectations, list the benefits in an easy-to-digest way, explain the different roles that are possible). Because of that, we may want to completely separate the regular application details and buttons from the other VP/PM applications - or at the very least, give them a distinct, interesting section of the page w more details than what we currently have in the FAQ.  

What do you think?

**Comment by AmandaNguye** [comment]
Add project information section. Text to be updated.
