### ISSUE TITLE
Docs page buttons 

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#56]
I noticed "Contents", "Get in touch", and "Dark Mode" are buttons (or appear to be buttons) on the docs page. Did you intend on them having a specific functionality?

**Comment by nurgul-ths** [comment]
They were links at first but they weren't going anywhere so I think I made them buttons to add some CSS rules. Should I style them differently and make links instead?

**Comment by Jhappy77** [comment]
I think since we will be making the Docs/Resources page just one page, we will just want them to be subheadings (not buttons or links), with a similar styling to what UBC Launchpad uses on their docs section.
