### ISSUE TITLE
Start CountUp when page is loaded

### ISSUE THREAD

**Issue by zNon18** [Tech-Start-UCalgary/tsu-website#60]
When users start the website, the numbers/stats trigger CountUp immediately. We need to find a way to make CountUp trigger when the user scrolls past the page or loads the page.

**Comment by Jhappy77** [comment]
@AmandaNguye We have react-visibility-sensor installed if I remember correctly. You can insert a visibility sensor in each numberstat, which triggers the countup. This should be simple to accomplish, although you should look at the npm pages for both to see what props of each component you'll need to use.
