### ISSUE TITLE
README: Helping future editors

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#71]
We need to help future maintainers take care of any content that is dynamic (content that should change year-to-year). Examples of this are the executive team and pm members, project info, event info. The README should detail how to edit this information.

This is not a huge priority (if we push it past the showcase deadline that's absolutely fine) but we will want it done eventually.

**Comment by Niyousha99** [comment]
Uodated README and added maintenance guide: https://github.com/Tech-Start-UCalgary/tsu-website/blob/main/maintenance-guide.md
