### ISSUE TITLE
Remove NumberStat hover effects

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#75]
I'm personally not a huge fan of the added hover effects on the NumberStats (especially making the stats larger upon hovering over them). We're already using hover effects quite a bit, so I think it may be wise to remove them. Thoughts?

**Comment by nurgul-ths** [comment]
I liked the hover effects on numbers but I think they are a bit abrupt on the text, maybe we can remove them partially?

**Comment by Jhappy77** [comment]
Yeah definitely remove them on the text- we can keep some hover effect on the numbers but it should be minor IMO

**Comment by Jhappy77** [comment]
I also noticed the hover effects for the numbers trigger far beyond the numbers themselves (when you are hovering on the div that surrounds them)
