### ISSUE TITLE
DOMNesting p Errors

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#79]
Our console spits many errors because there is a p tag which has many complicated descendants, which is unexpected behavior. Can you find the p tag that is causing this issue, and either remove it or change it to a div? This should solve the console errors. Don't worry about the other DOMnesting errors on your branch, I believe they are not present on the dev branch right now so you don't need to fix them.
![image](https://user-images.githubusercontent.com/45266424/116911879-b2877300-ac04-11eb-9240-0f240049f614.png)

**Comment by taylor-noel** [comment]
I fixed this one, but I just want to double-check do I have to worry about these two? 
![image](https://user-images.githubusercontent.com/61843554/116958722-c5c42e00-ac58-11eb-809b-b5b6359db1a3.png)

**Comment by Jhappy77** [comment]
Yeah don't worry about those, I'm pretty sure they are fixed on the main branch. If not, we'll look at them later
