### ISSUE TITLE
Carousel styles not reliant on autogenerated classes

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#84]
From our discord: The Carousel component auto-generates some css class names. We used these class names in our CSS, however, when we deploy, the deloyed Carousel autogenerates different class names for the same elements. To solve this issue, we need to change the CSS selectors for those rules to rely solely on the classes/information that won't change from our local system to our deploy.

**Comment by Niyousha99** [comment]
@Jhappy77 Can you verify whether this issue has been fixed?

**Comment by Jhappy77** [comment]
It works! Feel free to close this
