### ISSUE TITLE
Home Page hero height in mobile view

### ISSUE THREAD

**Issue by nurgul-ths** [Tech-Start-UCalgary/tsu-website#88]
The height of the hero section might look too long in mobile view, maybe we can shorten it a bit?

![Screenshot 2021-05-04 at 11 28 18](https://user-images.githubusercontent.com/79397892/116964033-483a0580-accc-11eb-8b93-71ff271d2c01.png)

**Comment by Jhappy77** [comment]
Yeah that looks odd. I think it's less of an issue on an actual mobile phone though- right now it uses a size of 100vh as the minimum (100% of the vertical height of the window) so squishing it on a computer looks weird. Take a look at the deployed website on your phone - I think it's less of an issue there, but we could still reduce it somewhat? Like 90vh?
