### ISSUE TITLE
Home Page header subtitle margin

### ISSUE THREAD

**Issue by nurgul-ths** [Tech-Start-UCalgary/tsu-website#89]
would it look better if we have a margin for both sides of the header subtitle?

![Screenshot 2021-05-04 at 11 28 18](https://user-images.githubusercontent.com/79397892/116964380-3442d380-accd-11eb-9bf4-008834de6fce.png)

**Comment by Jhappy77** [comment]
Yup, I think there should be a minimum margin here. Good catch!
