### ISSUE TITLE
Navbar dropdown menu 

### ISSUE THREAD

**Issue by nurgul-ths** [Tech-Start-UCalgary/tsu-website#90]
Can we make the dropdown menu disappear once you click on it?

![Screenshot 2021-05-04 at 11 40 24](https://user-images.githubusercontent.com/79397892/116964557-a4e9f000-accd-11eb-8040-c3940fdc694a.png)

**Comment by Jhappy77** [comment]
Yeah in my opinion it would be good to autodismiss it after pressing a link. Thoughts @rzwc @taylor-noel ?

**Comment by taylor-noel** [comment]
ya I agree

**Comment by rzwc** [comment]
Yes that's a great idea! That's how most dropdown menus I've seen work

**Comment by Jhappy77** [comment]
You can take this on- try and make the solution as simple as possible though!
