### ISSUE TITLE
Sizing the profiles on the team section

### ISSUE THREAD

**Issue by Jhappy77** [Tech-Start-UCalgary/tsu-website#95]
The project managers and executives in the team sections are sized differently; it may be nice to keep them consistent with each other.

EDIT: I just realized it's very hard to tell the difference between my screenshots because GitHub compresses them to be the same size anyways. The first set are at like 1800px and the second are at like 795px if you want to see what I'm talking about on your own device

![image](https://user-images.githubusercontent.com/45266424/117086156-0a0f0700-ad09-11eb-87d5-dc9237ac8666.png)
![image](https://user-images.githubusercontent.com/45266424/117086171-12674200-ad09-11eb-9829-1e77bbcc4ee4.png)
At large sizes, I prefer the way that the Project Managers are sized (there's a nice margin on the side)

At smaller screen sizes, I think the margin is less important, so I like how the execs are sized (PM's seem a little squished here)
![image](https://user-images.githubusercontent.com/45266424/117086239-46426780-ad09-11eb-816e-8394143b8b46.png)
![image](https://user-images.githubusercontent.com/45266424/117086255-4d697580-ad09-11eb-8541-8b566ddec6b9.png)

Could you take a look at this and write it so that they have the same (or very similar) sizing/margin rules, and so that there is more of a margin at high screen widths and less of one at low screen widths? The css clamp function could be useful. You can also look at the rules Amanda used for the homepage's margins in general. LMK if you think you can do this.

**Comment by Niyousha99** [comment]
I can take a look at this, but it won't be until after the showcase due to other priorities.

**Comment by Jhappy77** [comment]
Ok that's fine. Can you merge your Event stuff ASAP so I can take a look at it?

**Comment by Niyousha99** [comment]
Sorry, accidentally closed the issue. The events section is merged.

**Comment by Niyousha99** [comment]
Ok so from my understanding, you want the execs to have larger margins for larger screen widths and the PMs to have smaller margins for smaller screen widths, correct? Also to be consistent with the rest of the code I have written, 750px is the breakpoint between larger and smaller screen widths.

**Comment by Jhappy77** [comment]
Yup, that's correct, and we want the profiles for both to be the same size if possible.
